name: dart_application_1
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  google_generative_ai: ^0.4.3
  mysql_client: ^0.0.27

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
